/*
 * This file is autogenerated by autogen.pl. Do not edit this file by hand.
 */
#ifndef OMPI_FRAMEWORKS_H
#define OMPI_FRAMEWORKS_H

#include <opal/mca/base/mca_base_framework.h>

extern mca_base_framework_t ompi_allocator_base_framework;
extern mca_base_framework_t ompi_bcol_base_framework;
extern mca_base_framework_t ompi_bml_base_framework;
extern mca_base_framework_t ompi_btl_base_framework;
extern mca_base_framework_t ompi_coll_base_framework;
extern mca_base_framework_t ompi_crcp_base_framework;
extern mca_base_framework_t ompi_dpm_base_framework;
extern mca_base_framework_t ompi_fbtl_base_framework;
extern mca_base_framework_t ompi_fcoll_base_framework;
extern mca_base_framework_t ompi_fs_base_framework;
extern mca_base_framework_t ompi_io_base_framework;
extern mca_base_framework_t ompi_mpool_base_framework;
extern mca_base_framework_t ompi_mtl_base_framework;
extern mca_base_framework_t ompi_op_base_framework;
extern mca_base_framework_t ompi_osc_base_framework;
extern mca_base_framework_t ompi_pml_base_framework;
extern mca_base_framework_t ompi_pubsub_base_framework;
extern mca_base_framework_t ompi_rcache_base_framework;
extern mca_base_framework_t ompi_rte_base_framework;
extern mca_base_framework_t ompi_sbgp_base_framework;
extern mca_base_framework_t ompi_sharedfp_base_framework;
extern mca_base_framework_t ompi_topo_base_framework;
extern mca_base_framework_t ompi_vprotocol_base_framework;

static mca_base_framework_t *ompi_frameworks[] = {
    &ompi_allocator_base_framework,
    &ompi_bcol_base_framework,
    &ompi_bml_base_framework,
    &ompi_btl_base_framework,
    &ompi_coll_base_framework,
    &ompi_crcp_base_framework,
    &ompi_dpm_base_framework,
    &ompi_fbtl_base_framework,
    &ompi_fcoll_base_framework,
    &ompi_fs_base_framework,
    &ompi_io_base_framework,
    &ompi_mpool_base_framework,
    &ompi_mtl_base_framework,
    &ompi_op_base_framework,
    &ompi_osc_base_framework,
    &ompi_pml_base_framework,
    &ompi_pubsub_base_framework,
    &ompi_rcache_base_framework,
    &ompi_rte_base_framework,
    &ompi_sbgp_base_framework,
    &ompi_sharedfp_base_framework,
    &ompi_topo_base_framework,
    &ompi_vprotocol_base_framework,
    NULL
};

#endif /* OMPI_FRAMEWORKS_H */

